# Generated by Django 5.0.4 on 2024-04-06 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('city', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('steps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travels.steps')),
            ],
        ),
    ]
