# Generated by Django 5.0.4 on 2024-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='coordinates',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='steps',
            name='status',
            field=models.CharField(choices=[('done', 'DONE'), ('not_active', 'NOT_ACTIVE'), ('pending', 'PENDING')], default='NOT_ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='locations',
            name='status',
            field=models.CharField(choices=[('done', 'DONE'), ('not_active', 'NOT_ACTIVE'), ('pending', 'PENDING')], default='NOT_ACTIVE', max_length=10),
        ),
    ]
