# Generated by Django 5.0.4 on 2024-04-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='array_interval',
            field=models.JSONField(default={'time_ended': '1', 'time_started': '0'}),
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.location')),
            ],
        ),
    ]
