# Generated by Django 5.0.4 on 2024-04-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_steps_coordinates_steps_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/steps'),
        ),
    ]
