# Generated by Django 5.0.4 on 2024-04-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_steps_array_interval_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='array_interval',
            field=models.JSONField(default={}),
        ),
    ]
