# Generated by Django 5.0.4 on 2024-04-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_alter_steps_array_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='steps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.steps'),
        ),
    ]
