# Generated by Django 5.0.4 on 2024-04-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_remove_imagelocation_image_locations_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='steps',
        ),
        migrations.AddField(
            model_name='steps',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.locations'),
        ),
    ]
