# Generated by Django 5.0.4 on 2024-04-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_alter_location_steps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Locations',
        ),
    ]
