# Generated by Django 5.0.4 on 2024-04-06 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_remove_locations_steps_steps_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='image',
        ),
        migrations.AddField(
            model_name='imagelocation',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.locations'),
        ),
    ]
