# Generated by Django 5.0.4 on 2024-04-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_remove_locations_image_imagelocation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.locations'),
        ),
    ]
