# Generated by Django 5.0.4 on 2024-04-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_alter_steps_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_facility', models.CharField(choices=[('pitstop', 'PITSTOP'), ('hub', 'HUB'), ('resort', 'RESORT')], max_length=20)),
                ('square', models.CharField(max_length=20, verbose_name='Площадь')),
                ('MFZ', models.CharField(max_length=20, verbose_name='МФЗ')),
                ('cafe', models.IntegerField(verbose_name='Места для приготовления пищи')),
                ('distribution_center', models.CharField(max_length=50, verbose_name='Центр распределения')),
                ('STO', models.CharField(max_length=50, verbose_name='Станция тех. обслуживания')),
                ('power_charging', models.IntegerField(verbose_name='Электро зарядки')),
                ('market', models.CharField(max_length=20, verbose_name='Рынок')),
                ('tilt', models.CharField(max_length=20, verbose_name='Тент')),
                ('shower', models.IntegerField(verbose_name='Душ')),
                ('buildings', models.IntegerField(verbose_name='Модульные дома')),
                ('pitch', models.IntegerField(verbose_name='Питч-обычный')),
                ('pitch_vip', models.IntegerField(verbose_name='Питч-ВИП')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('employee_number', models.IntegerField(verbose_name='Количество вакансий')),
            ],
        ),
        migrations.AddField(
            model_name='locations',
            name='in_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
