# Generated by Django 5.0.4 on 2024-04-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_alter_steps_array_interval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='ImageLocation',
        ),
    ]
