# Generated by Django 5.0.4 on 2024-04-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_facility_locations_in_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='square',
            field=models.FloatField(max_length=20, verbose_name='Площадь'),
        ),
    ]
