# Generated by Django 5.0.4 on 2024-04-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_facility_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='facilities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='travels.facility'),
            preserve_default=False,
        ),
    ]
