# Generated by Django 5.0.4 on 2024-04-07 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_locations_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='facilities',
        ),
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='travels.locations'),
            preserve_default=False,
        ),
    ]
