# Generated by Django 5.0.4 on 2024-04-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_remove_locations_facilities_facility_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
        migrations.AlterField(
            model_name='facility',
            name='type_facility',
            field=models.CharField(choices=[('pitstop', 'PITSTOP'), ('hub', 'HUB'), ('resort', 'RESORT')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
