# Generated by Django 5.0.4 on 2024-04-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_facility_id_alter_facility_type_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='location',
            new_name='locations',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
        migrations.AlterField(
            model_name='facility',
            name='type_facility',
            field=models.CharField(choices=[('pitstop', 'PITSTOP'), ('hub', 'HUB'), ('resort', 'RESORT')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
