# Generated by Django 5.0.4 on 2024-04-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0015_rename_location_facility_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='travels.facility'),
        ),
    ]
