# Generated by Django 5.0.4 on 2024-04-07 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0017_facility_id_alter_facility_type_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='travels.locations'),
        ),
    ]
