# Generated by Django 5.0.4 on 2024-04-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='age',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
