# Generated by Django 5.0.4 on 2024-04-07 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='offers/')),
            ],
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('quest_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='quests/')),
            ],
        ),
        migrations.AlterField(
            model_name='subuser',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='gameavatars/'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
