# Generated by Django 5.0.4 on 2024-04-07 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subuser_id_alter_subuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
