# Generated by Django 4.2.5 on 2024-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
