# Generated by Django 5.0.4 on 2024-04-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_subuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Quests',
        ),
        migrations.DeleteModel(
            name='SubUser',
        ),
    ]
