# Generated by Django 5.0.4 on 2024-04-06 02:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitstop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitstop',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=(1, 1), max_length=180, srid=4326),
        ),
    ]
