# Generated by Django 5.0.4 on 2024-04-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitstop', '0002_pitstop_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitstop',
            name='coordinates',
        ),
    ]
